### ISSUE TITLE
Demo.py missing from repo

### ISSUE THREAD

**Issue by AnuUMBC** [ds-kiel/LimitNet#2]
The repo is missing demo.py. Can the authors please provide the code to transmit images via LoRa?

**Comment by miralys1** [comment]
Thank you for bringing this to our attention. We have now pushed the demo.py file to the repository.

Additionally, as mentioned in the paper, we simulate the network with the bandwidth range of LoRaWAN, which is why we do not provide any code for transmitting images via LoRa. 

If you have any further questions, please feel free to ask.
